//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda_express.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.lista_venta = new HashSet<lista_venta>();
        }
    
        public int id { get; set; }
        public byte[] foto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> cat_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual ICollection<lista_venta> lista_venta { get; set; }
    }
}
