//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda_express.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo
    {
        public tipo()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
