//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda_express.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.lista_venta = new HashSet<lista_venta>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dia_venta { get; set; }
        public Nullable<double> sub_total { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> total { get; set; }
        public string usuario_id { get; set; }
    
        public virtual ICollection<lista_venta> lista_venta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
